import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { IonApp } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  alertCircleOutline,
  arrowBackOutline,
  arrowForwardOutline,
  bookmark,
  bookmarkOutline,
  bookOutline,
  checkmarkCircleOutline,
  chevronBackOutline,
  chevronForwardOutline,
  closeOutline,
  cloudUploadOutline,
  documentAttachOutline,
  documentOutline,
  documentsOutline,
  downloadOutline,
  eyeOutline,
  fileTrayFullOutline,
  folderOpenOutline,
  gridOutline,
  helpCircleOutline,
  homeOutline,
  listOutline,
  logOutOutline,
  menuOutline,
  notificationsOutline,
  personOutline,
  pulseOutline,
  searchOutline,
  shareSocialOutline,
  statsChartOutline,
  trashOutline,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [IonApp, RouterOutlet],
  template: '<ion-app><router-outlet /></ion-app>',
})
export class App {
  constructor() {
    addIcons({
      alertCircleOutline,
      arrowBackOutline,
      arrowForwardOutline,
      bookmark,
      bookmarkOutline,
      bookOutline,
      checkmarkCircleOutline,
      chevronBackOutline,
      chevronForwardOutline,
      closeOutline,
      cloudUploadOutline,
      documentAttachOutline,
      documentOutline,
      documentsOutline,
      downloadOutline,
      eyeOutline,
      fileTrayFullOutline,
      folderOpenOutline,
      gridOutline,
      helpCircleOutline,
      homeOutline,
      listOutline,
      logOutOutline,
      menuOutline,
      notificationsOutline,
      personOutline,
      pulseOutline,
      searchOutline,
      shareSocialOutline,
      statsChartOutline,
      trashOutline,
    });
  }
}
